### ISSUE TITLE
Error when deploying the program

### ISSUE THREAD

**Issue by Siu03** [Ansh-Rathod/Flutter-Musive-app#1]
`lib/main.dart:73:19: Error: The parameter 'axisDirection' of the method
'NoGlowBehavior.buildOverscrollIndicator' has type 'AxisDirection', which does not match the
corresponding type, 'ScrollableDetails', in the overridden method,
'ScrollBehavior.buildOverscrollIndicator'.
 - 'AxisDirection' is from 'package:flutter/src/painting/basic_types.dart'
 ('/C:/flutter/packages/flutter/lib/src/painting/basic_types.dart').
 - 'ScrollableDetails' is from 'package:flutter/src/widgets/scrollable.dart'
 ('/C:/flutter/packages/flutter/lib/src/widgets/scrollable.dart').
Change to a supertype of 'ScrollableDetails', or, for a covariant parameter, a subtype.
    AxisDirection axisDirection,
                  ^
/C:/flutter/packages/flutter/lib/src/widgets/scroll_configuration.dart:156:10: Context: This is the
overridden method ('buildOverscrollIndicator').
  Widget buildOverscrollIndicator(BuildContext context, Widget child, ScrollableDetails details) {`

I was watching your program because it caught my attention but when I followed the steps it gave me an error.

Actually your program is too good, I have only seen it through the README images.

**Comment by Ansh-Rathod** [comment]
you can remove that block of code. haven't tested this app for a while. the code is causing problems and is harmless for the app.

**Comment by Siu03** [comment]
LGTM
